# Generated by Django 3.2 on 2021-04-11 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='limit',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 1, 39, 24, 605803, tzinfo=utc), verbose_name='Submit limit'),
        ),
    ]
