# Generated by Django 3.2 on 2021-04-11 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0002_task_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='limit',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 2, 5, 56, 792950, tzinfo=utc), verbose_name='Submit limit'),
        ),
    ]
